name: Packer Builds

on:
  push:
    branches-ignore: [main]
  pull_request:
    branches: [develop, main]

jobs:
  build:
    runs-on: macos-10.15
    strategy:
      max-parallel: 4
      matrix:
        packer_distro:
          - distro: Debian
            template: debian-buster64.json
          - distro: Rocky
            template: rocky8.json

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - uses: actions/cache@v2
        with:
          path: ~/Library/Caches/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt
          pip install pre-commit

      - name: Validate Ansible Version
        run: ansible --version

      - name: Validate Packer Version
        run: packer --version

      - name: Validate VirtualBox Version
        run: VBoxManage --version

      - name: Validate Packer Templates
        run: |
          cd ${{ matrix.packer_distro.distro }}
          packer validate -syntax-only ${{ matrix.packer_distro.template }}
